# -*- coding: utf-8 -*-
"""Christine Khayat-Sensor Generator Starter Notebook

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u85_fTqSMe4JaLlKwxAe7V1oNG6NQXhC

# 🌊 Water Sensor Data Generator

**Welcome!** In this notebook, you'll build a mock water sensor that generates realistic data for Hydroficient's HYDROLOGIC devices.

## What You'll Create
- A `WaterSensor` class that generates readings
- Timestamps in ISO 8601 format (UTC)
- Sequential counters for replay attack detection
- Realistic pressure and flow rate values
- Anomalies for testing (leak, blockage, stuck sensor)

## Expected Output Format
```json
{
  "device_id": "GM-HYDROLOGIC-01",
  "timestamp": "2024-01-15T14:30:45.123456+00:00",
  "counter": 42,
  "pressure_upstream": 82.3,
  "pressure_downstream": 76.8,
  "flow_rate": 41.2
}
```

---

## Step 1: Import Required Libraries
"""

import random
import json
from datetime import datetime, timezone

print("Libraries imported successfully!")

"""## Step 2: Create the WaterSensor Class

Complete the `WaterSensor` class below. You need to:

1. Initialize `device_id` and `counter` in `__init__`
2. Generate realistic sensor values in `get_reading()`
3. Create anomaly methods for testing
"""

class WaterSensor:
    """
    Simulates a Hydroficient HYDROLOGIC water sensor.

    Normal ranges:
    - pressure_upstream: 75-90 PSI
    - pressure_downstream: 70-85 PSI
    - flow_rate: 30-50 gallons/min
    """

    def __init__(self, device_id):

        self.device_id = device_id
        self.counter = 0
        self.base_pressure_up = 82.0
        self.base_pressure_down = 76.0
        self.base_flow = 40.0

    def get_reading(self):

        self.counter += 1
        return {
            "device_id": self.device_id,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "counter": self.counter,
            "pressure_upstream": round(self.base_pressure_up + random.uniform(-2, 2), 1),
            "pressure_downstream": round(self.base_pressure_down + random.uniform(-2, 2), 1),
            "flow_rate": round(self.base_flow + random.uniform(-3, 3), 1)
        }

    def get_leak_reading(self):

       reading = self.get_reading()
       reading["flow_rate"] = round(random.uniform(80, 120), 1)
       return reading

    def get_blockage_reading(self):
        reading = self.get_reading()
        reading["pressure_upstream"] = round(random.uniform(85, 95), 1)
        reading["pressure_downstream"] = round(random.uniform(30, 50), 1)
        return reading

    def get_stuck_reading(self):
         reading = self.get_reading()
         stuck_value = 82.0
         reading["pressure_upstream"] = stuck_value
         reading["pressure_downstream"] = stuck_value
         reading["flow_rate"] = stuck_value
         return reading

"""## Step 3: Test Your Sensor

Run this cell to test your implementation. You should see:
- Counters incrementing from 1 to 5
- Timestamps in ISO format
- Pressure values around 75-90 (upstream) and 70-85 (downstream)
- Flow rate around 30-50
"""

# Test your sensor
sensor = WaterSensor("GM-HYDROLOGIC-01")

print("=== Testing Normal Readings ===")
for i in range(5):
    reading = sensor.get_reading()
    print(f"Reading {i+1}: Counter={reading['counter']}, "
          f"Pressure Up={reading['pressure_upstream']}, "
          f"Flow={reading['flow_rate']}")

print("\n=== Testing Anomalies ===")
print(f"Leak: {sensor.get_leak_reading()}")
print(f"Blockage: {sensor.get_blockage_reading()}")
print(f"Stuck: {sensor.get_stuck_reading()}")

"""## Step 4: Generate 100 Readings

Now generate your dataset:
- 97 normal readings
- 1 leak reading
- 1 blockage reading  
- 1 stuck sensor reading

Shuffle them so anomalies aren't all at the end!
"""

# Generate the dataset
sensor = WaterSensor("GM-HYDROLOGIC-01")
readings = []

# TODO: Generate 97 normal readings
for _ in range(97):
    readings.append(sensor.get_reading())

# TODO: Add 3 anomalies
readings.append(sensor.get_leak_reading())
readings.append(sensor.get_blockage_reading())
readings.append(sensor.get_stuck_reading())

# Shuffle to mix anomalies in
random.shuffle(readings)

print(f"Generated {len(readings)} readings!")
print(f"First reading: {readings[0]}")
print(f"Last reading: {readings[-1]}")

"""## Step 5: Save to JSON File

Save your readings to a JSON file that you can download.'''
"""

# Save to JSON file
filename = "sensor_data.json"

with open(filename, "w") as f:
    json.dump(readings, f, indent=2)

    print(f"✅ Saved {len(readings)} readings to {filename}")

    # Show file size
    import os
    size = os.path.getsize(filename)
    print(f"📁 File size: {size:,} bytes")

"""## Step 6: Download Your File

Run this cell to download your sensor_data.json file.
"""

# Download the file (Colab only)
from google.colab import files
files.download("sensor_data.json")

print("🎉 Download started! Check your Downloads folder.")

"""---

## ✅ Checklist Before Submitting

- [ ] Counter increments correctly (1, 2, 3, ...)
- [ ] Timestamps are in ISO 8601 UTC format
- [ ] Pressure values are in realistic ranges
- [ ] Flow rate is in realistic range
- [ ] You have 100 total readings
- [ ] You included at least 3 anomalies
- [ ] JSON file downloads successfully

**Great job!** 🎉 You've built your first IoT sensor simulator!
"""