# -*- coding: utf-8 -*-
"""Christine Khayat-Control Flow in Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vsSk7ZXRaL_sqw5lLNGKctLyhmkOUWNp

# Control Flow in Python - Colab Notebook

## Introduction to Control Flow

Control flow refers to the order in which individual statements, instructions, or function calls are executed or evaluated in a programming language. In Python, control flow is managed using decision-making statements, loops, and jump statements. Understanding control flow is essential for writing logical and efficient code.

### Table of Contents

1. Decision-Making Statements
2. Loops
3. Jump Statements
4. Real-World Examples
5. Exercises

## Decision-Making Statements

Decision-making statements allow your program to make decisions and execute different code blocks based on certain conditions. This is essential for creating dynamic and responsive programs.

### 1. If Statements

The `if` statement allows you to execute a block of code only if a certain condition is met. If the condition evaluates to `True`, the code block under the `if` statement runs. If it evaluates to `False`, the code block is skipped.

**Syntax:**

```python
if condition:
    # code block
```

Here is a simple example below:
"""

a = 1

# condition is true
if a==1:
  print('Inside if-case')

"""**Try making your own example for an if-case below:**"""

## Try writing an if statement
a = 1
b = 10
if a < b:
  print('a is less than b')

"""**Example:**
Imagine you have a program that checks if a user is eligible for a discount.
"""

# Check eligibility for discount
age = 20

if age < 18:
    print("You are eligible for a child discount.")

"""**Explanation:**
- If the condition `age < 18` is true, the message "You are eligible for a child discount." is printed.

### 2. If-Else Statements

The `if-else` statement allows you to execute one block of code if the condition is true and another block of code if the condition is false.

**Syntax:**

```python
if condition:
    # code block if condition is True
else:
    # code block if condition is False
```

**Example:**
Let's check if a number is positive or negative.
"""

number = -10

if number >= 0:
    print("The number is positive.")
else:
    print("The number is negative.")

"""**Explanation:**
- If the condition `number >= 0` is false, the message "The number is negative." is printed.

### 3. If-Elif-Else Statements

The `if-elif-else` statement allows you to check multiple conditions. If the first condition is false, it moves on to check the next condition, and so on.

**Syntax:**
```python
if condition1:
    # code block if condition1 is True
elif condition2:
    # code block if condition2 is True
else:
    # code block if all conditions are False
```

**Example:**
Checking the grade of a student based on their score.
"""

score = 85

if score >= 90:
    print("Grade: A")
elif score >= 80:
    print("Grade: B")
elif score >= 70:
    print("Grade: C")
elif score >= 60:
    print("Grade: D")
else:
    print("Grade: F")

"""**Explanation:**
- The `elif` keyword stands for "else if" and allows you to check multiple conditions sequentially.

### 4. Nested If Statements

You can use nested `if` statements to check multiple conditions within another `if` statement.

**Syntax:**
```python
if condition1:
    if condition2:
        # code block if both condition1 and condition2 are True
```

**Example:**
Imagine you are managing a loyalty program. You want to check if a user is a premium member and if they have enough points for a reward.
"""

# Real-world example
is_premium_member = True
points = 120

if is_premium_member:
    if points >= 100:
        print("You are eligible for a reward!")

else:
    print("You need to be a premium member to be eligible for rewards.")

"""**Explanation:**
- The outer `if` statement checks if the user is a premium member.
- The inner `if` statement checks if the user has enough points for a reward.

**Example:** Check whether the given year is a leap year or not?
"""

#Nested if statement, which checks for condition upon satisfying parent condition
year = int(input("Enter the year: "))
if (year%4 == 0):
    if (year%100 == 0):
        if (year%400 ==0):
            print ("It is a leap year")
        else:
            print ("It is not a leap year")
    else:
        print("It is a leap year")
else:
    print("It is not a leap year")

"""### 5. Multiple Conditions

You can combine multiple conditions in an `if` statement using logical operators (`and`, `or`, `not`).

**Syntax:**
```python
if condition1 and condition2:
    # code block if both condition1 and condition2 are True

if condition1 or condition2:
    # code block if either condition1 or condition2 is True

if not condition:
    # code block if condition is False
```

**Example:**
Imagine you are creating a library system. You want to check if a user can borrow a book based on their membership status and if they have returned all previous books.
"""

# Real-world example
is_member = True
has_returned_books = True

if is_member and has_returned_books:
    print("You can borrow a new book.")
else:
    print("You cannot borrow a new book.")

"""**Explanation:**
- The `and` operator ensures that both conditions (`is_member` and `has_returned_books`) must be true for the code block to execute.

## Loops

Loops are used to repeat a block of code multiple times. Python provides two main types of loops: `for` loops and `while` loops. Loops are useful for tasks that require repetitive actions, such as iterating over a list of items or executing a block of code until a condition is met.

### For Loops

A `for` loop is used to iterate over a sequence (like a list, tuple, or string) and execute a block of code for each item in the sequence.

**Syntax:**
```python
for item in sequence:
    # code block
```

**Example 1: Iterating Over a List**
Imagine you are creating a program to display the top 5 scores in a game.
"""

# Real-world example
scores = [100, 95, 90, 85, 80]

for score in scores:
    print(f"Score: {score}")

"""**Explanation:**
- The loop iterates over each item in the `scores` list and prints the score.

**Example 2: Finding the Sum of Even Numbers in a List**
You want to calculate the sum of all even numbers in a list.
"""

# Real-world example
numbers = [1, 2, 3, 4, 5, 6]
even_sum = 0

for number in numbers:
    if number % 2 == 0:
        even_sum += number

print(f"Sum of even numbers: {even_sum}")

"""**Explanation:**
- The loop iterates over each number in the `numbers` list.
- The `if` statement checks if the number is even, and if so, adds it to `even_sum`.

**Example 3: Iterating Over a Dictionary**
You want to print the name and age of each person in a dictionary.
"""

# Real-world example
people = {"Alice": 25, "Bob": 30, "Charlie": 35}

for name, age in people.items():
    print(f"{name} is {age} years old.")

"""**Explanation:**
- The loop iterates over each key-value pair in the `people` dictionary and prints the name and age.

### While Loops

A `while` loop is used to execute a block of code as long as a condition is true.

**Syntax:**
```python
while condition:
    # code block
```

**Example 1: Printing the First 10 Positive Integers**
You want to print the first 10 positive integers.
"""

# Real-world example
number = 1

while number <= 10:
    print(number)
    number += 1

"""**Explanation:**
- The loop continues as long as `number` is less than or equal to 10.
- The `number` variable is incremented by 1 in each iteration.

**Example 2: Simulating a Login System**
You want to keep asking for a username and password until the correct credentials are entered.
"""

# Real-world example
correct_username = "admin"
correct_password = "admin123"

username = ""
password = ""

while username != correct_username or password != correct_password:
    username = input("Enter username: ")
    password = input("Enter password: ")

print("Login successful!")

"""**Explanation:**
- The loop continues as long as the entered username and password do not match the correct credentials.

### Nested Loops

You can use loops inside other loops. These are called nested loops.

**Example: Displaying a Pattern**
You want to print a pattern of stars in a square shape.
"""

# Real-world example
size = 5

for i in range(size):
    for j in range(size):
        print("*", end=" ")
    print()

"""**Explanation:**
- The outer loop iterates over the rows.
- The inner loop iterates over the columns and prints a star.

## Jump Statements

### 1. Break Statement

The `break` statement is used to exit a loop prematurely. It is often used to terminate a loop when a specific condition is met.

**Example: Exiting a Loop When a Certain Condition is Met**
You want to find the first number greater than 50 in a list.
"""

# Real-world example
numbers = [10, 20, 30, 40, 50, 60, 70]

for number in numbers:
    if number > 50:
        print(f"Found a number greater than 50: {number}")
        break

"""**Explanation:**
- The loop stops executing once a number greater than 50 is found.

### 2. Continue Statement

The `continue` statement skips the current iteration and moves to the next iteration of the loop.

**Example: Skipping Odd Numbers**
You want to print all even numbers from 1 to 10.
"""

# Real-world example
for number in range(1, 11):
    if number % 2 != 0:
        continue
    print(number)

"""**Explanation:**
- The loop skips printing odd numbers and only prints even numbers.

### 3. Pass Statement

The `pass` statement is a null operation. It is used as a placeholder in loops or functions where code is syntactically required but you don't want to execute any code.

**Example: Using Pass in a Loop**
You want to create a loop that will be implemented later.
"""

# Real-world example
for i in range(5):
    pass  # To be implemented later

"""**Explanation:**
- The loop runs 5 times but does not execute any code inside the loop.

### Real-World Example: Grocery List Manager

Let's create a simple grocery list manager using loops and conditional statements. The program will allow the user to add items to the list, remove items from the list, and display the list.
"""

# Grocery List Manager

grocery_list = []

while True:
    print("\n1. Add item")
    print("2. Remove item")
    print("3. Display list")
    print("4. Exit")
    choice = input("Enter your choice: ")

    if choice == "1":
        item = input("Enter the item to add: ")
        grocery_list.append(item)
        print(f"{item} added to the list.")
    elif choice == "2":
        item = input("Enter the item to remove: ")
        if item in grocery_list:
            grocery_list.remove(item)
            print(f"{item} removed from the list.")
        else:
            print(f"{item} not found in the list.")
    elif choice == "3":
        print("\nGrocery List:")
        for item in grocery_list:
            print(f"- {item}")
    elif choice == "4":
        break
    else:
        print("Invalid choice. Please try again.")

"""**Explanation:**
- The program allows the user to add, remove, and display items in a grocery list.
- The loop continues until the user chooses to exit.

## Exercises: Practice Your Control Flow Skills!

Now that you've got a handle on control flow in Python, it's time to practice what you've learned! Below are a set of exercises that will help you reinforce your understanding of decision-making statements, loops, and jump statements. Try to solve them on your own, and remember, experimenting is the key to mastering Python!

### Exercise 1: Even or Odd

Write a program that asks the user to enter a number and prints whether the number is even or odd.
"""

n=int(input('Enter a number: '))

if n % 2 == 0:
   print('number is even')
else:
  print('number is odd')

"""### Exercise 2: Guess the Number

Create a simple guessing game where the computer randomly selects a number between 1 and 100, and the user has to guess the number. The program should give hints if the guess is too high or too low, and end when the user guesses the correct number.
"""

import random

number = random.randint(1, 100)

while True:
  guess=int(input("Guess the number"))
  if guess < number :
   print("the number is too low")
  elif guess > number :
   print('the number is too high')
  else:
   print("YOu have guessed the number! Congratz")
   break

"""### Exercise 3: Print Prime Numbers

Write a program that prints all prime numbers between 1 and 50.
"""

for n in range(2, 51):
    prime = True

    for i in range(2, n):
        if n % i == 0:
            prime = False

    if prime:
        print(n, "is a prime number")

"""### Exercise 4: Factorial Calculation

Create a function that calculates the factorial of a given number using a `while` loop.
"""

def factorial(n):
 result =1

 while n>1:
   result=result*n
   n=n-1

 return result

number=int(input('Enter a number: '))
print("Factorial:", factorial(number))

"""### Exercise 5: Multiplication Table

Write a program that prints the multiplication table for a given number up to 10 using a `for` loop.
"""

number=int(input("Enter a number: "))

for n in range(1,11):
  answer= number * n
  print(number,"x",n,'=',answer)

"""### Exercise 6: Count Vowels in a String

Write a program that counts the number of vowels in a given string using a `for` loop and the `continue` statement.
"""

text=input("Write a string: ")
count=0

for letter in text:
  if letter not in "aeiou":
    continue

  count=count+1
print('number of vowels: ', count)

"""Remember, the more you practice, the better you’ll understand how to manipulate and utilize Python’s capabilities. Have fun with these exercises, and try creating some of your own variations!"""