# -*- coding: utf-8 -*-
"""Christine Khayat-Defining Functions in Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xjEB8l7kY4RZJRYPU3GvMOihY5dUHynY

# Functions in Python - Colab Notebook

#### Introduction to Functions

A function is a block of code that performs a specified task. Functions help organize your code and make it more readable, maintainable, and reusable.

## Table of Contents

1. Why Use Functions?
2. Types of Functions
    - Nothing goes in, nothing comes out.
    - Nothing goes in, something comes out.
    - Something goes in, nothing comes out.
    - Something goes in, something comes out.
3. Interesting Examples and Use Cases
4. Try It Yourself
5. Exercises

## Why Use Functions?

- **Readability**: Functions make a program easier to read and understand.
- **Reduction in Code Duplication**: Functions reduce code duplication.
- **Reusability**: Functions allow the code to be reused.

Most of the time, we provide some arguments to a function, and it returns something. However, this may not always be the case. When writing a function, we need to decide if the function needs any arguments or not, and if the function needs to return something or not.

## Syntax of Functions

The basic syntax for defining a function in Python is as follows:
"""

def function_name(parameters):
    """
    Optional: Docstring to describe the function.
    """
    # Code block
    return result  # Optional: return statement

"""* `def`: This keyword is used to declare a function.
* `function_name`: This is the name of the function. It should be descriptive and follow standard naming conventions.
* `parameters`: These are the inputs to the function. They are optional and can be zero or more.
* `'''Docstring'''`: This is an optional string to describe what the function does.
* `return`: This is an optional statement to return a value from the function.

### Example: Write a function that echoes the input that it takes.
"""

# we use the def keyword
# then write the function name
# then define the function inputs
def echo(user_input):

  # this will print whatever is sent to this function
  print(user_input)

echo('Hello World')

echo('An apple a day keeps anyone away, if you throw it hard enough.')

"""Broadly, we can classify the combination of function parameters and their return types as follows:

### Types of Functions

#### 1. Nothing Goes In, Nothing Comes Out

This type of function neither takes any input nor returns any output.

**Example:**
"""

def greet():
    print("Hello, world!")

# Calling the function
greet()

"""**Explanation:**
- The `greet` function does not take any arguments and does not return anything. It simply prints a message.

#### 2. Nothing Goes In, Something Comes Out

This type of function does not take any input but returns an output.

**Example:**
"""

def get_pi():
    return 3.14159

# Calling the function and storing the return value in a variable
pi_value = get_pi()
print(f"Value of Pi: {pi_value}")

"""**Explanation:**
- The `get_pi` function does not take any arguments but returns the value of Pi.

#### 3. Something Goes In, Nothing Comes Out

This type of function takes input but does not return any output.

**Example:**
"""

def greet_person(name):
    print(f"Hello, {name}!")

# Calling the function with an argument
greet_person("Alice")

"""**Explanation:**
- The `greet_person` function takes a `name` as an argument and prints a personalized greeting message.

#### 4. Something Goes In, Something Comes Out

This type of function takes input and returns an output.

**Example:**
"""

def add_numbers(a, b):
    return a + b

# Calling the function with arguments and storing the return value in a variable
sum_result = add_numbers(5, 3)
print(f"Sum: {sum_result}")

"""**Explanation:**
- The `add_numbers` function takes two arguments, `a` and `b`, and returns their sum.

### Interesting Examples and Use Cases

**Example: Calculating the Area of a Circle**
You want to create a function that calculates the area of a circle given its radius.
"""

def calculate_area(radius):
    pi = 3.14159
    return pi * (radius ** 2)

# Calling the function with an argument and printing the result
area = calculate_area(5)
print(f"Area of the circle: {area}")

"""### Try It Yourself

**Example: Calculating the Average of a List**

You want to create a function that calculates the average of a list of numbers.

"""

def calculate_average(numbers):
  total=0

  for number in numbers:
     total=int(total+number)
     average=int(total/len(numbers))
  return average


# Output expected: 30
my_numbers = [10, 20, 30, 40, 50]
average = calculate_average(my_numbers)
print(f"Average: {average}")

# Output expected: 25
your_numbers = [5, 15, 25, 35, 45]
your_average = calculate_average(your_numbers)
print(f"Your average: {your_average}")

"""### Exercises

**Exercise 1: Convert Temperature**
Write a function that converts a temperature from Celsius to Fahrenheit.
"""

def celsius_to_fahrenheit(celsius):
    Fahrenheit =int((Celsius * 9/5) + 32)
    return Fahrenheit
 # Test the function
Celsius=int(input("Enter the Temp in celsius: "))
temp_fahrenheit = celsius_to_fahrenheit(25)
print(f"Temperature in Fahrenheit: {temp_fahrenheit}")

"""**Exercise 2: Check Even or Odd**
Write a function that checks whether a given number is even or odd.

Function name should be `is_even` and it should take a number as input.  
"""

def is_even(n):

  if n % 2 == 0:
   return "It is an even number"
  else:
   return "It is an odd number"


numbers=int(input("Enter a number: "))
print(is_even(numbers))

"""**Exercise 3: Find Maximum**
Write a function that returns the maximum of two numbers.

"""

def find_Max(a,b):
  if a<b:
    return b
  else:
    return a

a=int(input("Enter a number: "))
b=int(input("Enter another number: "))
print(find_Max(a,b))

"""**Exercise 4: Calculate Factorial**
Write a function that calculates the factorial of a given number.
"""

def factorial(n):
    result = 1

    for i in range(1, n + 1):
        result = result * i

    return result


number = int(input("Enter a number: "))

print(factorial(number))

"""
**Exercise 5: Reverse a String**
Write a function that reverses a given string."""

def reverse_string(text):
    return text[::-1]

text = input("Enter a string: ")
print(reverse_string(text))

"""**Exercise 6: Count Vowels in a String**
Write a function that counts the number of vowels in a given string.
"""

def count_vowels(text):
    count = 0

    for letter in text:
        if letter in "aeiou":
            count = count + 1

    return count


text = input("Enter a string: ")

print(count_vowels(text))

"""### Conclusion

Functions are an essential part of programming in Python. They help you organize your code, reduce duplication, and make your programs more modular and easier to understand. Practice creating and using functions to enhance your programming skills and make your code more efficient.
"""