# -*- coding: utf-8 -*-
"""Christine Khayat-Data Structures in Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PZP7rYeiCdzYxLE9nciYhAXadyaQLo6L

### Data Structures in Python - Colab Notebook

### Introduction to Data Structures

Python provides a variety of built-in data structures that make it easy to store, organize, and manipulate data. In this notebook, we will explore the most commonly used data structures: lists, tuples, sets, and dictionaries. We will also dive into slicing and indexing, which are essential for accessing and modifying elements within these data structures.

## Table of Contents

1. Lists
    - Creating Lists
    - Accessing Elements
    - Modifying Elements
    - List Methods
2. Tuples
    - Creating Tuples
    - Accessing Elements
    - Immutability
    - Tuple Methods
3. Sets
    - Creating Sets
    - Adding and Removing Elements
    - Set Operations
4. Dictionaries
    - Creating Dictionaries
    - Accessing Elements
    - Modifying Elements
    - Dictionary Methods
5. Slicing and Indexing
    - Slicing Lists and Strings
    - Indexing with Tuples
    - Advanced Slicing Techniques

## Lists

A list is an ordered collection of items that can be of any type. Lists are mutable, which means you can change their content.

#### Creating Lists
"""

# Creating a list of integers
numbers = [1, 2, 3, 4, 5]
print(numbers)

# Creating a list of mixed types
mixed = [1, "hello", 3.14, True]
print(mixed)

"""Now try defining a list of your own and play with it. See what happens when you add two lists, subtract two lists, multiply lists with a number."""

# Experiment with lists

even_numbers=[0,2,4,6,8,10]
print(even_numbers)

odd_numbers=[1,3,5,7,9,11]
print(odd_numbers)

numbers=even_numbers+odd_numbers
print(numbers)

numbers=sorted(even_numbers+odd_numbers)
print(numbers)

numbers.remove(2)
numbers.remove(6)
numbers.append(22)

print(numbers)

multiply_numbersby2=[x*2 for x in numbers]
numbers=multiply_numbersby2
print(multiply_numbersby2)

multiple_numbers=numbers*2
print(multiple_numbers)

"""### Accessing Elements

Always remember that in programming languages first element is at position 0 not at 1. So if you call `numbers[0]`, this will return the first item in the list.
"""

# Accessing elements by index
numbers=[1,2,3,4,5,6,7,8,9]
print(numbers[0])  # First element
print(numbers[1])  # Second element

"""Interestingly python also provides something called [negative indexing](https://www.w3schools.com/python/gloss_python_string_negative_indexing.asp). Here we start with -1 for the last element and then move our way from left to right. For your reference:

![Python List Indexing - Positive and Negative](https://drive.google.com/uc?id=1bO4tUSChRh12AQ5aGyeLUNbioEdOHwz2)
"""

numbers=[1,2,3,4,5,6,7,8,9]
print(numbers[-1])  # Last element

# Accessing a range of elements (slicing)
print(numbers[1:4])  # Elements from index 1 to 3

"""Try experimenting with indexing and slicing and get a good feel for it.

### Modifying Elements - CHenaging, adding and removing elements in a list
"""

# Changing an element
numbers[2] = 10
print(numbers)

# Adding elements
numbers.append(6)
print(numbers)

# Removing elements
numbers.remove(10)
print(numbers)

"""### List Methods"""

# List of available methods
print(dir(numbers))

# Using some common list methods
numbers = [3, 1, 4, 1, 5, 9]
numbers.sort()
print("Sorted list:", numbers)

numbers.reverse()
print("Reversed list:", numbers)

index = numbers.index(5)
print("Index of 5:", index)

"""## Tuples

A tuple is an ordered collection of items that can be of any type. Tuples are immutable, which means their content cannot be changed.

### Creating Tuples

"""

# Creating a tuple
my_tuple = (1, 2, 3, "hello")
print(my_tuple)

# Creating a tuple without parentheses (not recommended)
my_tuple = 1, 2, 3, "hello"
print(my_tuple)

"""### Accessing Elements"""

# Accessing elements by index
print(my_tuple[0])  # First element
print(my_tuple[-1])  # Last element

"""### Immutability"""

# Trying to change an element (will raise an error)
# my_tuple[1] = 4  # Uncommenting this line will cause an error

# Creating a new tuple with changed content
new_tuple = my_tuple[:1] + (4,) + my_tuple[2:]
print(new_tuple)

"""### Tuple Methods"""

# Tuple of methods (limited compared to lists)
print(dir(my_tuple))

# Using some common tuple methods
count = my_tuple.count("hello")
print("Count of 'hello':", count)

index = my_tuple.index(3)
print("Index of 3:", index)

"""## Sets

A set is an unordered collection of unique items. Sets are mutable, but the elements themselves must be immutable.

### Creating Sets
"""

# Creating a set
my_set = {1, 2, 3, 3, 4}
print(my_set)  # Duplicate elements are removed

# Creating an empty set
empty_set = set()
print(empty_set)

"""### Adding and Removing Elements"""

# Adding elements
my_set.add(5)
print(my_set)

# Removing elements
my_set.remove(3)
print(my_set)

"""### Set Operations"""

# Set operations
set_a = {1, 2, 3}
set_b = {3, 4, 5}

union = set_a | set_b
print("Union:", union)

intersection = set_a & set_b
print("Intersection:", intersection)

difference = set_a - set_b
print("Difference:", difference)

symmetric_difference = set_a ^ set_b
print("Symmetric Difference:", symmetric_difference)

"""## Dictionaries

A dictionary is an unordered collection of key-value pairs. Keys must be unique and immutable, while values can be of any type.

### Creating Dictionaries
"""

# Creating a dictionary
my_dict = {"name": "Alice", "age": 25, "city": "New York"}
print(my_dict)

# Creating an empty dictionary
empty_dict = {}
print(empty_dict)

"""### Accessing Elements"""

# Accessing elements by key
print(my_dict["name"])  # Accessing value by key

# Using the get method
print(my_dict.get("age"))

"""
### Modifying Elements"""

# Changing a value
my_dict["age"] = 26
print(my_dict)

# Adding a new key-value pair
my_dict["email"] = "alice@example.com"
print(my_dict)

# Removing a key-value pair
del my_dict["city"]
print(my_dict)

"""### Dictionary Methods"""

# Dictionary methods
print(dir(my_dict))

# Using some common dictionary methods
keys = my_dict.keys()
print("Keys:", keys)

values = my_dict.values()
print("Values:", values)

items = my_dict.items()
print("Items:", items)

"""## Slicing and Indexing

Slicing and indexing are powerful techniques for accessing and modifying elements within lists, tuples, and strings.

Slicing and indexing are very useful in python and it is important that you get used to them. Here is a great video tutorial for the same:

<br>
<center>
  <a href="https://www.youtube.com/watch?v=ajrtAuDg3yw" target="_blank">
  <img alt='Thumbnail for a video showing 3 cool Google Colab features' src= 'https://drive.google.com/uc?id=1eFhFgyZW4yKi-EPtgLu5Z7aMsbkNX2p0' width="700">

  </a>
</center>

### Slicing Lists and Strings
"""

# List slicing
numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(numbers[2:5])  # Elements from index 2 to 4
print(numbers[:4])   # Elements from start to index 3
print(numbers[4:])   # Elements from index 4 to end
print(numbers[::2])  # Every second element

# String slicing
my_string = "Hello, world!"
print(my_string[7:12])  # Substring "world"
print(my_string[:5])    # Substring "Hello"
print(my_string[7:])    # Substring "world!"
print(my_string[::-1])  # Reversed string

# Experiment with slicing. Create your own questions and get comfortable with indexing
numbers=[2004,9,25]
print("my birthday is on :", numbers[::-1])
a_string="rebmetpes fo ht52 eht no si yadhtrib s'enitsirhc"
print(a_string[::-1])

"""### Indexing with Tuples"""

# Tuple indexing
my_tuple = (10, 20, 30, 40, 50)
print(my_tuple[1])   # Second element
print(my_tuple[-1])  # Last element

# Tuple slicing
print(my_tuple[1:4])  # Elements from index 1 to 3
print(my_tuple[:3])   # First three elements
print(my_tuple[2:])   # Elements from index 2 to end

"""### Advanced Slicing Techniques"""

# Negative indexing
print(numbers[-5:])     # Last five elements
print(numbers[:-5])     # All but the last five elements

# Reversing with slicing
print(numbers[::-1])    # Reversed list

"""## Exercises

**Exercise 1: List Operations**
Create a list of your favorite fruits and perform the following operations:
- Add a new fruit to the list.
- Remove a fruit from the list.
- Sort the list alphabetically.
- Print the first and last fruit in the list.
"""

#creation of a new list
fruits=['banana','mango','apple','orange']
#adding new fruit
fruits.append('kiwi')
#removing of a fruit
fruits.remove('apple')
print(fruits)
#sorting
fruits.sort()
print(fruits)
#printing first and last
print('1st and last fruit:', fruits[0], fruits[-1])

"""**Exercise 2: Tuple Operations**
Create a tuple with five different numbers and perform the following operations:
- Access the second and fourth elements.
- Create a new tuple by adding an element to the original tuple.
- Count the occurrences of a specific number in the tuple.
"""

#creation of tupel
number_tupeled=(1,2,3,4,5,5)
print(number_tupeled)
#access of 2nd and 4th element
print('2nd element: ',number_tupeled[1])
print('4th element: ',number_tupeled[3])
#new tuple with an additional element
new_tuple = number_tupeled[:5] + (8,) + number_tupeled[-1:]
print(new_tuple)
#count occurrences
print('the occurrence of no.5: ',new_tuple.count(5))

"""**Exercise 3: Set Operations**
Create two sets with some common and some unique elements. Perform the following operations:
- Find the union of the sets.
- Find the intersection of the sets.
- Find the difference between the sets.
- Find the symmetric difference between the sets.
"""

set_Christine = {2, 5, 0, 9}
set_Khayat = {2, 0, 4}

union = set_Christine | set_Khayat
print("union:", union)

intersection = set_Christine & set_Khayat
print("Intersection:", intersection)

difference = set_Christine - set_Khayat
print("Difference:", difference)

symmetric_difference = set_Christine ^ set_Khayat
print("Symmetric Difference:", symmetric_difference)

"""**Exercise 4: Dictionary Operations**
Create a dictionary with information about a book (title, author, year). Perform the following operations:
- Add a new key-value pair for the genre.
- Update the year of publication.
- Remove the author from the dictionary.
- Print all the keys and values in the dictionary.
"""

# Creating a dictionary about book(title,author,year)
Book_dict = {"title": "sanditon", "author": 'Jane Austen', "year": 1816}
print(Book_dict)
#new key-genre

Book_dict["genre"] = "Romance Novel"
print(Book_dict)

#update year
Book_dict["year"]=1817
print(Book_dict)

# Removing the author
del Book_dict["author"]
print(Book_dict)

#printing it all out
print(Book_dict)

"""**Exercise 5: Slicing and Indexing**
Given a list of numbers from 1 to 20, perform the following operations:
- Print the first five elements.
- Print the last five elements.
- Print every second element.
- Print the list in reverse order.
"""

#list of number
numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

#first five elements
print(numbers[0:5])

#last 5 elements
print(numbers[-5:])

# Every second element
print("Every 2nd element:",numbers[::2])

#reverse
print("Reverse list:",numbers[::-1])

"""
## Conclusion

Understanding data structures is essential for efficient programming in Python. Lists, tuples, sets, and dictionaries provide powerful ways to store and manipulate data. Mastering slicing and indexing techniques will further enhance your ability to work with these data structures. Practice with the examples and exercises provided to deepen your understanding and improve your programming skills."""