listener 8883
#bind_address localhost

# TLS Certificate Configuration
cafile certs/ca.pem
certfile certs/server.pem
keyfile certs/server-key.pem
require_certificate true 

# Client certificate requirement
require_certificate false

# Authentication
allow_anonymous true

# Logging
log_type all
log_dest stdout